name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

        # Authenticate with Docker Hub
      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        # Pull the latest image from Docker Hub
      - name: Pull latest Docker image
        run: docker pull victoramorimchagas/ci-cd-test:latest

        # Build Docker image
      - name: Build Docker image
        run: docker build -t ci-cd-test .

        # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push victoramorimchagas/ci-cd-test:latest

        # SSH into EC2 instance and deploy Docker image
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -q --filter "publish=3000") || true
            docker pull victoramorimchagas/ci-cd-test:latest
            docker run -d -p 3000:3000 victoramorimchagas/ci-cd-test:latest


