name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Navigate to project directory
        run: cd $GITHUB_WORKSPACE

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Add other steps for building Docker image, pushing to Docker Hub, etc.

